// 分類配置，包含色彩、圖標、描述等
export const categoryConfig = {
  'history': { 
    name: '歷史',
    name_en: 'History',
    name_es: 'Historia',
    description: '從史前時代到現代，台灣歷史的完整脈絡',
    description_en: 'A complete narrative of Taiwan\'s history from prehistoric times to the modern era',
    description_es: 'Una narrativa completa de la historia de Taiwán desde la prehistoria hasta la era moderna',
    icon: 'history',
    color: '#92400e',
    colorLight: '#f59e0b20',
    gradient: 'linear-gradient(135deg, #92400e, #d97706)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Presidential_Office_Building_%28Taiwan%29.jpg/640px-Presidential_Office_Building_%28Taiwan%29.jpg',
  },
  'geography': { 
    name: '地理',
    name_en: 'Geography',
    name_es: 'Geografía',
    description: '台灣的自然環境、地形特色與區域發展',
    description_en: 'Taiwan\'s natural environment, terrain features, and regional development',
    description_es: 'El entorno natural, características del terreno y desarrollo regional de Taiwán',
    icon: 'geography',
    color: '#065f46',
    colorLight: '#059f4620',
    gradient: 'linear-gradient(135deg, #065f46, #10b981)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Taroko_national_park.jpg/640px-Taroko_national_park.jpg',
  },
  'culture': { 
    name: '文化',
    name_en: 'Culture',
    name_es: 'Cultura',
    description: '多元族群文化的融合與在地特色',
    description_en: 'The fusion of diverse ethnic cultures and local characteristics',
    description_es: 'La fusión de diversas culturas étnicas y características locales',
    icon: 'culture',
    color: '#7c3aed',
    colorLight: '#7c3aed20',
    gradient: 'linear-gradient(135deg, #7c3aed, #a855f7)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Lukang_Tianhou_Temple.JPG/640px-Lukang_Tianhou_Temple.JPG',
  },
  'food': { 
    name: '美食',
    name_en: 'Food',
    name_es: 'Gastronomía',
    description: '從夜市小吃到精緻料理的美食文化',
    description_en: 'Culinary culture from night market street food to fine dining',
    description_es: 'Cultura culinaria desde la comida callejera del mercado nocturno hasta la alta cocina',
    icon: 'food',
    color: '#ea580c',
    colorLight: '#ea580c20',
    gradient: 'linear-gradient(135deg, #ea580c, #f97316)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Taipei_Shilin_Night_Market.jpg/640px-Taipei_Shilin_Night_Market.jpg',
  },
  'art': { 
    name: '藝術',
    name_en: 'Art',
    name_es: 'Arte',
    description: '傳統工藝到當代藝術的創作能量',
    description_en: 'Creative energy from traditional crafts to contemporary art',
    description_es: 'Energía creativa desde artesanías tradicionales hasta arte contemporáneo',
    icon: 'art',
    color: '#be185d',
    colorLight: '#be185d20',
    gradient: 'linear-gradient(135deg, #be185d, #ec4899)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Taipei_Fine_Arts_Museum_2019.jpg/640px-Taipei_Fine_Arts_Museum_2019.jpg',
  },
  'music': { 
    name: '音樂',
    name_en: 'Music',
    name_es: 'Música',
    description: '從原住民音樂到流行音樂的聲音風景',
    description_en: 'A sonic landscape from indigenous music to pop music',
    description_es: 'Un paisaje sonoro desde la música indígena hasta la música pop',
    icon: 'music',
    color: '#0891b2',
    colorLight: '#0891b220',
    gradient: 'linear-gradient(135deg, #0891b2, #06b6d4)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/National_Concert_Hall%2C_Taipei_2015.jpg/640px-National_Concert_Hall%2C_Taipei_2015.jpg',
  },
  'technology': { 
    name: '科技',
    name_en: 'Technology',
    name_es: 'Tecnología',
    description: '科技島的創新發展與數位轉型',
    description_en: 'Innovation and digital transformation on the technology island',
    description_es: 'Innovación y transformación digital en la isla de la tecnología',
    icon: 'technology',
    color: '#1d4ed8',
    colorLight: '#1d4ed820',
    gradient: 'linear-gradient(135deg, #1d4ed8, #3b82f6)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/TSMC_Fab12.jpg/640px-TSMC_Fab12.jpg',
  },
  'nature': { 
    name: '自然',
    name_en: 'Nature',
    name_es: 'Naturaleza',
    description: '豐富的生態環境與環保議題',
    description_en: 'Rich ecosystems and environmental conservation topics',
    description_es: 'Ecosistemas ricos y temas de conservación ambiental',
    icon: 'nature',
    color: '#15803d',
    colorLight: '#15803d20',
    gradient: 'linear-gradient(135deg, #15803d, #22c55e)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Yushan_main_peak%2BBlue_arrow.jpg/640px-Yushan_main_peak%2BBlue_arrow.jpg',
  },
  'people': { 
    name: '人物',
    name_en: 'People',
    name_es: 'Personas',
    description: '影響台灣發展的重要人物與故事',
    description_en: 'Key figures and stories that shaped Taiwan\'s development',
    description_es: 'Figuras clave e historias que dieron forma al desarrollo de Taiwán',
    icon: 'people',
    color: '#b45309',
    colorLight: '#b4530920',
    gradient: 'linear-gradient(135deg, #b45309, #f59e0b)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Ang_Lee_-_66%C3%A8me_Festival_de_Venise_%28Mostra%29.jpg/400px-Ang_Lee_-_66%C3%A8me_Festival_de_Venise_%28Mostra%29.jpg',
  },
  'society': { 
    name: '社會',
    name_en: 'Society',
    name_es: 'Sociedad',
    description: '社會變遷與當代議題的深度探討',
    description_en: 'In-depth exploration of social change and contemporary issues',
    description_es: 'Exploración profunda del cambio social y temas contemporáneos',
    icon: 'society',
    color: '#475569',
    colorLight: '#47556920',
    gradient: 'linear-gradient(135deg, #475569, #64748b)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Legislative_Yuan%2C_the_Republic_of_China.JPG/640px-Legislative_Yuan%2C_the_Republic_of_China.JPG',
  },
  'economy': { 
    name: '經濟',
    name_en: 'Economy',
    name_es: 'Economía',
    description: '經濟奇蹟的成因與轉型挑戰',
    description_en: 'The drivers behind the economic miracle and transformation challenges',
    description_es: 'Los motores detrás del milagro económico y los desafíos de transformación',
    icon: 'economy',
    color: '#c2410c',
    colorLight: '#c2410c20',
    gradient: 'linear-gradient(135deg, #c2410c, #ea580c)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Taipei_101_from_afar.jpg/400px-Taipei_101_from_afar.jpg',
  },
  'lifestyle': { 
    name: '生活',
    name_en: 'Lifestyle',
    name_es: 'Estilo de Vida',
    description: '台灣人的生活方式與價值觀',
    description_en: 'The lifestyle and values of the Taiwanese people',
    description_es: 'El estilo de vida y los valores del pueblo taiwanés',
    icon: 'lifestyle',
    color: '#4d7c0f',
    colorLight: '#4d7c0f20',
    gradient: 'linear-gradient(135deg, #4d7c0f, #65a30d)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/7-Eleven_in_Taipei.jpg/640px-7-Eleven_in_Taipei.jpg',
  }
};

export type CategoryKey = keyof typeof categoryConfig;

export function getCategoryConfig(category: string): typeof categoryConfig[CategoryKey] | null {
  return categoryConfig[category as CategoryKey] || null;
}